/*
 * Decompiled with CFR 0_118.
 */
/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class du {
    public static String a = "";
    public static String b = "Members object";
    public static String c = "Take";
    public static String d = "Drop";
    public static String e = "Hidden";
    public static String f = "Ok";
    public static String g = "Select";
    public static String h = "Continue";
    public static String i = "Discard";
    public static String j = "Trust this computer";
    public static String k = "for 30 days: ";
    public static String l = "Loading - please wait.";
    public static String m = "Connection lost";
    public static String n = "Please wait - attempting to reestablish";
    public static String o = "Starting game engine...";
    public static String p = "Prepared visibility map";
    public static String q = "Connecting to update server";
    public static String r = "Checking for updates - ";
    public static String s = "Loaded update list";
    public static String t = "Prepared sound engine";
    public static String u = "Loading fonts - ";
    public static String v = "Loaded fonts";
    public static String w = "Loading title screen - ";
    public static String x = "Loaded title screen";
    public static String y = "Loading config - ";
    public static String z = "Loaded config";
    public static String A = "Loading sprites - ";
    public static String B = "Loaded sprites";
    public static String C = "Loading textures - ";
    public static String D = "Loaded textures";
    public static String E = "Loaded input handler";
    public static String F = "Loading wordpack - ";
    public static String G = "Loaded wordpack";
    public static String H = "Loading interfaces - ";
    public static String I = "Loaded interfaces";
    public static String J = "Please enter a 6-digit PIN.";
    public static String K = "You have only just left another world.";
    public static String L = "Your profile will be transferred in:";
    public static String M = " seconds.";
    public static String N = "Connection timed out.";
    public static String O = "Please try using a different world.";
    public static String P = "";
    public static String Q = "";
    public static String R = "Error connecting to server.";
    public static String S = "";
    public static String T = "No response from server.";
    public static String U = "Please try using a different world.";
    public static String V = "";
    public static String W = "That username or password is incorrect. Please";
    public static String X = "create an account at www.os-scape.com/register";
    public static String Y = "or double check your credentials and try again.";
    public static String Z = "Your account has been disabled.";
    public static String aa = "<col=ffffff>Click here</col> to post an appeal on our forums.";
    public static String ab = "";
    public static String ac = "Your account is already logged in.";
    public static String ad = "Try again in 60 secs...";
    public static String ae = "";
    public static String af = "OS-Scape has been updated!";
    public static String ag = "Please reload this page.";
    public static String ah = "";
    public static String ai = "This world is full.";
    public static String aj = "Please use a different world.";
    public static String ak = "";
    public static String al = "Unable to connect.";
    public static String am = "Login server offline.";
    public static String an = "";
    public static String ao = "Login limit exceeded.";
    public static String ap = "Too many connections from your address.";
    public static String aq = "";
    public static String ar = "Unable to connect.";
    public static String as = "Bad session id.";
    public static String at = "";
    public static String au = "We suspect someone knows your password.";
    public static String av = "Press 'change your password' on front page.";
    public static String aw = "";
    public static String ax = "You need a members account to login to this world.";
    public static String ay = "Please subscribe, or use a different world.";
    public static String az = "";
    public static String aA = "Could not complete login.";
    public static String aB = "Please try using a different world.";
    public static String aC = "";
    public static String aD = "The server is being updated.";
    public static String aE = "Please wait 1 minute and try again.";
    public static String aF = "";
    public static String aG = "Too many login attempts.";
    public static String aH = "Please wait a few minutes before trying again.";
    public static String aI = "";
    public static String aJ = "You are standing in a members-only area.";
    public static String aK = "To play on this world move to a free area first";
    public static String aL = "";
    public static String aM = "Account locked as we suspect it has been stolen.";
    public static String aN = "Press 'recover a locked account' on front page.";
    public static String aO = "";
    public static String aP = "This world is running a closed Beta.";
    public static String aQ = "Sorry invited playerCount only.";
    public static String aR = "Please use a different world.";
    public static String aS = "Invalid loginserver requested.";
    public static String aT = "Please try using a different world.";
    public static String aU = "";
    public static String aV = "Malformed login packet.";
    public static String aW = "Please try again.";
    public static String aX = "";
    public static String aY = "No reply from loginserver.";
    public static String aZ = "Please wait 1 minute and try again.";
    public static String ba = "";
    public static String bb = "Error loading your profile.";
    public static String bc = "Please contact customer support.";
    public static String bd = "";
    public static String be = "Unexpected loginserver response.";
    public static String bf = "Please try using a different world.";
    public static String bg = "";
    public static String bh = "This computers address has been blocked";
    public static String bi = "as it was used to break our rules.";
    public static String bj = "";
    public static String bk = "";
    public static String bl = "Service unavailable.";
    public static String bm = "";
    public static String bn = "";
    public static String bo = "Please enter your username/email address.";
    public static String bp = "";
    public static String bq = "";
    public static String br = "Please enter your password.";
    public static String bs = "";
    public static String bt = "Your account must have a displayname set";
    public static String bu = "in order to play the game.  Please set it";
    public static String bv = "via the website, or the main game.";
    public static String bw = "Your attempt to log into your account was";
    public static String bx = "unsuccessful.  Don't worry, you can sort";
    public static String by = "this out by visiting the billing system.";
    public static String bz = "Your account is currently inaccessible.";
    public static String bA = "Please try again in a few minutes.";
    public static String bB = "";
    public static String bC = "You need to vote to play!";
    public static String bD = "Visit OS-Scape.com and vote,";
    public static String bE = "and then come back here!";
    public static String bF = "Sorry, but your account is not eligible to";
    public static String bG = "play this version of the game.  Please try";
    public static String bH = "playing the main game instead!";
    public static String bI = "Enter the 6-digit code generated by your";
    public static String bJ = "authenticator app.";
    public static String bK = "";
    public static String bL = "The code you entered was incorrect.";
    public static String bM = "Please try again.";
    public static String bN = "";
    public static String bO = "Unexpected server response";
    public static String bP = "Please try using a different world.";
    public static String bQ = "";
    public static String bR = " has logged in.";
    public static String bS = " has logged out.";
    public static String bT = "Unable to find ";
    public static String bU = "Use";
    public static String bV = "Examine";
    public static String bW = "Attack";
    public static String bX = "Choose Option";
    public static String bY = " more options";
    public static String bZ = "Walk here";
    public static String ca = "level-";
    public static String cb = "skill-";
    public static String cc = "Please wait...";
    public static String cd = "Close";
    public static String ce = " ";
    public static String cf = "M";
    public static String cg = "K";
    public static String ch = "Your friend list is full. Max of 200 for free users, and 400 for members";
    public static String ci = " is already on your friend list";
    public static String cj = "Your ignore list is full. Max of 100 for free users, and 400 for members";
    public static String ck = " is already on your ignore list";
    public static String cl = "You can't add yourself to your own friend list";
    public static String cm = "You can't add yourself to your own ignore list";
    public static String cn = "Please remove ";
    public static String co = " from your ignore list first";
    public static String cp = "Please remove ";
    public static String cq = " from your friend list first";
    public static String cr = "yellow:";
    public static String cs = "yellow:";
    public static String ct = "red:";
    public static String cu = "red:";
    public static String cv = "green:";
    public static String cw = "green:";
    public static String cx = "cyan:";
    public static String cy = "cyan:";
    public static String cz = "purple:";
    public static String cA = "purple:";
    public static String cB = "white:";
    public static String cC = "white:";
    public static String cD = "flash1:";
    public static String cE = "flash1:";
    public static String cF = "flash2:";
    public static String cG = "flash2:";
    public static String cH = "flash3:";
    public static String cI = "flash3:";
    public static String cJ = "glow1:";
    public static String cK = "glow1:";
    public static String cL = "glow2:";
    public static String cM = "glow2:";
    public static String cN = "glow3:";
    public static String cO = "glow3:";
    public static String cP = "wave:";
    public static String cQ = "wave:";
    public static String cR = "wave2:";
    public static String cS = "wave2:";
    public static String cT = "shake:";
    public static String cU = "shake:";
    public static String cV = "scroll:";
    public static String cW = "scroll:";
    public static String cX = "slide:";
    public static String cY = "slide:";
    public static String cZ = "OS-Scape is loading - please wait...";
    public static String da = "Please enter your account username & password.";
    public static String db = "<col=ffffff>Warning!";
    public static String dc = "Authenticator";
    public static String dd = "<u=ff>Can't Log In?</u>";
    public static String de = "Connecting to server...";
    public static String df = "Login: ";
    public static String dg = "Password: ";
    public static String dh = "PIN: ";
    public static String di = "Welcome to OS-Scape";
    public static String dj = "New User";
    public static String dk = "Existing User";
    public static String dl = "Login";
    public static String dm = "Cancel";
    public static String dn = "Forgotten your password? <col=ffffff>Click here.";
    public static String do = "Forgotten your password?";
    public static String dp = "Username/email: ";
    public static String dq = "Recover";
    public static String dr = "Back";
    public static String ds = "Please enter your username.";
    public static String dt = "If you created your account after November";
    public static String du = "2010, this will be the creation email address.";
    public static String dv = "Page has opened in a new window.";
    public static String dw = "(Please check your popup blocker.)";
    public static String dx = "Error connecting to server.";
    public static String dy = "The part of the website you are trying";
    public static String dz = "to connect to is offline at the moment.";
    public static String dA = "Please try again later.";
    public static String dB = "Sorry, there was an error trying to";
    public static String dC = "log you in to this part of the website.";
    public static String dD = "Please try again later.";
    public static String dE = "Error connecting to server.";
    public static String dF = "You must enter a valid login to proceed. For accounts";
    public static String dG = "created after 24th November 2010, please use your";
    public static String dH = "email address. Otherwise please use your username.";
    public static String dI = "Select a world";
    public static String dJ = "Members only world";
    public static String dK = "Free world";
    public static String dL = "World";
    public static String dM = "Players";
    public static String dN = "Location";
    public static String dO = "Type";
    public static String dP = "OFF";
    public static String dQ = "FULL";
    public static String dR = "Loading...";
    public static String dS = "Click to switch";
    public static String dT = "First time playing OS-Scape? <col=ffffff>Click here.";
    public static String dU = "<col=ffff00>You have selected to play the <col=ff0000>PvP</col><col=ffff00> world. To";
    public static String dV = "<col=ffff00>play the Realism or Economy world, simply select";
    public static String dW = "<col=ffff00>You have selected to play the <col=ff0000>Realism</col><col=ffff00> world. To";
    public static String dX = "<col=ffff00>play the PVP or Economy world, simply select";
    public static String dY = "<col=ffff00>You have selected to play the <col=00cc00>Economy</col><col=ffff00> world. To";
    public static String dZ = "<col=ffff00>play the Realism or PVP world, simply select";
    public static String ea = "<col=ffff00>it from the world list.";

    du() {
        throw new Error();
    }

    public static int a(String string) {
        return string.length() + 1;
    }
}

